obstacle_range: 5.0
raytrace_range: 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: ir_of_robot
inflation_radius: 2.0

observation_sources: laser_scan_sensor #, point_cloud_sensor

laser_scan_sensor: {sensor_frame: lidar_base_1, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}